In [4]:
import numpy as np  

# Creating Arrays

In [ ]:
np.zeros(5)  #creates an array of 5 zeros  # np.zeros(size)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(5)     # creates an array of 5 ones  # np.ones(size)

array([1., 1., 1., 1., 1.])

In [9]:
np.full(5, 7)  # creates an array of 5 sevens  # np.full(size, value)

array([7, 7, 7, 7, 7])

In [10]:
np.array([1, 2, 3])  # creates an array from a list  # np.array(list)

array([1, 2, 3])

In [14]:
a = np.array([1, 2, 3, 4, 5])  
a[2]  # accesses the third element (index 2)
a[4] = 10  # modifies the fifth element (index 4) to 10

In [15]:
a

array([ 1,  2,  3,  4, 10])

In [16]:
np.arange(5)  # creates an array of numbers from 0 to 4  # np.arange(size)

array([0, 1, 2, 3, 4])

In [17]:
np.linspace(0, 1, 11)  # creates an array of 11 evenly spaced numbers from 0 to 1  # np.linspace(start, stop, num)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
np.linspace(0,  100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi Dimensional Arrays

In [ ]:
np.zeros((5 ,2))  # creates a 5x2 array of zeros  # np.zeros((rows, cols)) # 2d array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]) 

In [23]:
n[0, 1]  # accesses the element in the first row and second column (index 0, 1)

np.int64(2)

In [26]:
n[0, 1] = 20 
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [28]:
n[0]  # used to acces the whole first row of the array (index 0)

array([ 1, 20,  3])

In [30]:
n[2] = [30, 40, 50]  # modifies the third row (index 2) to [30, 40, 50]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [30, 40, 50]])

In [32]:
n[ : ]  # accesses all rows of the array

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [30, 40, 50]])

In [33]:
n[ : , 1]  # accesses all rows of the second column (index 1)

array([20,  5, 40])

In [35]:
n[: , 2] = [100, 200, 300]  # modifies the third column (index 2) to [100, 200, 300]
n

array([[  1,  20, 100],
       [  4,   5, 200],
       [ 30,  40, 300]])

# Randomly Generated Arrays

In [38]:
np.random.seed(2)  # sets the random seed for reproducibility
np.random.rand(5, 2 )  # creates a 5x2 array of random numbers between 0 and 1  # np.random.rand(rows, cols)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [40]:
np.random.seed(2) 
np.random.randn(5, 2)  # creates a 5x2 array of random numbers from a standard normal distribution (mean=0, std=1)  # np.random.randn(rows, cols)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [41]:
np.random.seed(2)
np.random.randint(low = 0, high = 10, size=(5, 2))  # creates a 5x2 array of random integers between 0 and 9 (inclusive)  # np.random.randint(low, high, size=(rows, cols))

array([[8, 8],
       [6, 2],
       [8, 7],
       [2, 1],
       [5, 4]], dtype=int32)

# Elemetwise Operation

In [43]:
a = np.arange(1, 6)  # creates an array of numbers from 1 to 5  # np.arange(start, stop)        

In [ ]:
a + 10  # adds 10 to each element of the array
a * 100  # multiplies each element of the array by 100
a / 2  # divides each element of the array by 2
a - 1  # subtracts 1 from each element of the array
(10 - (a * 2)) ** 5  # performs a series of operations on the array: multiplies each element by 2, subtracts from 10, and raises to the power of 5

array([32768,  7776,  1024,    32,     0])

In [50]:
b = (10 - (a * 2)) ** 5
a + b  # adds the two arrays element-wise

array([32769,  7778,  1027,    36,     5])

# Comparision Operators

In [51]:
a >= 2 

array([False,  True,  True,  True,  True])

In [52]:
b

array([32768,  7776,  1024,    32,     0])

In [53]:
a > b

array([False, False, False, False,  True])

In [55]:
a[a > b]  # returns the elements of array a that are greater than the corresponding elements in array b

array([5])

# Summarizing operations

In [56]:
a

array([1, 2, 3, 4, 5])

In [57]:
a.min()  # returns the minimum value in the array

np.int64(1)

In [58]:
a.max()  # returns the maximum value in the array

np.int64(5)

In [59]:
a.sum()  # returns the sum of all elements in the array

np.int64(15)

In [60]:
a.mean()  # returns the mean (average) of all elements in the array

np.float64(3.0)

In [61]:
a.std()  # returns the standard deviation of all elements in the array

np.float64(1.4142135623730951)