In [1]:
import numpy as np

# Vecotr Operations

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
u

array([2, 4, 5, 6])

In [7]:
2*u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 2, 3, 4])

In [5]:
u 

array([2, 4, 5, 6])

In [6]:
u + v

array([ 3,  6,  8, 10])

# Multiplication

Vector Vector Multiplication

In [11]:
def vector_vector_multiplication(u, v):
    assert u.shape == v.shape                                    # Vector-vector multiplication is only defined for vectors of the same shape
    n = u.shape[0]
    result = 0
    for i in range(n):
        result = result + u[i] * v[i]
    return result        


In [12]:
vector_vector_multiplication(u, v)

np.int64(49)

In [ ]:
u.dot(v)       # Dot product of two vectors using numpy's built-in function

np.int64(49)

In [41]:
U = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [42]:
U.shape

(3, 2)

In [47]:
v = np.array([10, 20])

Matrix Vector Multiplication

In [48]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]                              # Matrix-vector multiplication is only defined for matrices and vectors of compatible shapes
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)      # Multiply each row of the matrix by the vector
    return result
    

In [49]:
matrix_vector_multiplication(U,v)

array([ 50., 110., 170.])

In [50]:
U.dot(v)

array([ 50, 110, 170])

Matrix Matrix Multiplication

In [75]:
U = np.array([
    [1, 2],
    [3, 4]
])                 

In [76]:
U.shape

(2, 2)

In [74]:
V = np.array([
    [5, 6],
    [7, 8]
])

In [77]:
V.shape

(2, 2)

In [78]:
def matrix_matrix_multiplication(U, v):
    assert U.shape[1] == V.shape[0]                              # Matrix-matrix multiplication is only defined for matrices of compatible shapes
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:, i]                                                # Get the i-th column of the second matrix
        Uvi = matrix_vector_multiplication(U, vi)                       # Multiply the first matrix by the i-th column of the second matrix
        result[:, i] = Uvi                                         # Store the result in the i-th column of the result matrix
    return result

In [79]:
matrix_matrix_multiplication(   U, V)

array([[19., 22.],
       [43., 50.]])

In [80]:
U.dot(V)

array([[19, 22],
       [43, 50]])

# Identity Matrix

In [91]:
I = np.eye(2)    # Identity matrix of size 2x2

In [90]:
I

array([[1., 0.],
       [0., 1.]])

In [87]:
V


array([[5, 6],
       [7, 8]])

In [88]:
V.dot(I)

array([[5., 6.],
       [7., 8.]])

# Inverse

In [95]:
VS = V[[0, 1]]
VS

array([[5, 6],
       [7, 8]])

In [103]:
VS_inverse = np.linalg.inv(VS)      # Compute the inverse of the matrix VS  # here linald is a linear algebra module in numpy that provides functions for performing various linear algebra operations, including computing the inverse of a matrix.
VS_inverse

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [105]:
VS_inverse.dot(VS)  # Multiplying a matrix by its inverse should yield the identity matrix.

array([[ 1.00000000e+00, -3.55271368e-15],
       [ 3.55271368e-15,  1.00000000e+00]])